### ISSUE TITLE
Does not work in Hassio 0.81.2

### ISSUE THREAD

**Issue by phellarv** [mgejke/asyncsector#2]
Wed Oct 31 2018 22:26:13 GMT+0100 (Central European Standard Time)

```
Error during setup of component sector_alarm
Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/asyncsector/asyncsector.py", line 36, in login
    AsyncSector.Base + AsyncSector.Login, json=self._auth)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 391, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 757, in start
    message, payload = await self._protocol.read()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/streams.py", line 543, in read
    await self._waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/sector_alarm.py", line 65, in async_setup
    if not await async_sector.login():
  File "/config/deps/lib/python3.6/site-packages/asyncsector/asyncsector.py", line 42, in login
    return True
  File "/usr/local/lib/python3.6/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.6/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
```

**Comment by phellarv** [comment]
I got one more error now:

Wed Oct 31 2018 22:32:42 GMT+0100 (Central European Standard Time)

```
Error during setup of component sector_alarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/sector_alarm.py", line 77, in async_setup
    load_platform(hass, 'sensor', DOMAIN)
TypeError: load_platform() missing 2 required positional arguments: 'discovered' and 'hass_config'
```

**Comment by phellarv** [comment]
Rolled back to 0.81.0 and now it's working.

**Comment by phellarv** [comment]
Probably this change: https://github.com/home-assistant/home-assistant/pull/17952

**Comment by endor-force** [comment]
The bug is not in asyncsector it is in the home-assistant component.
https://github.com/mgejke/hass-sectoralarm

**Comment by mgejke** [comment]
I'm aware, will look into it as soon as possible, and yes, it's in hass-sectoralarm.
