### ISSUE TITLE
Timeout creates issues..

### ISSUE THREAD

**Issue by endor-force** [mgejke/asyncsector#8]
The timeout in asyncsector causes issues and the plaform fail to set up.
I tried to raise the timeout value but the only solution that works for me is to remove the statment for timeout completely.
Not sure if my Pi3 setup is extremely slow or why this continues to fail for me.
Seem to be others having similar problem in the hass community thread as well though.

```
2019-06-27 21:24:44 ERROR (MainThread) [homeassistant.setup] Error during setup of component sector_alarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/asyncsector/asyncsector.py", line 36, in login
    AsyncSector.Base + AsyncSector.Login, json=self._auth)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "uvloop/loop.pyx", line 1945, in create_connection
  File "uvloop/loop.pyx", line 1942, in uvloop.loop.Loop.create_connection
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/sector_alarm/__init__.py", line 58, in async_setup
    if not await async_sector.login():
  File "/usr/local/lib/python3.7/site-packages/asyncsector/asyncsector.py", line 42, in login
    return True
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError```

**Comment by mgejke** [comment]
The timeout exist so that it won't get stuck forever (mostly as a precaution...).
Is this still a problem? Do you have thermometers configured and how many? They seem to be really slow.

**Comment by endor-force** [comment]
Yep it's still there, I have updated to a pi4 and it seems to work a little better but fails every third reboot or so. 

I have three thermometers that is imported.
Sometimes I only get the alarm status without the thermometers.
The status is really lagging as well even in the app in the phone now so they might have throttled the API calls down or something.

**Comment by phellarv** [comment]
I have exactly the opposite. The app is much faster now, and it takes 3-4 seconds to update the status of my lock, alarm and thermometers. Opposed to atleast 20-30 seconds before the last update. What version of the app do you have? (I have 2.0.12)

**Comment by endor-force** [comment]
Exact opposite indeed. :)
I have 2.0.13, android.

**Comment by mgejke** [comment]
Is this still an issue? Don't have any problems myself...

**Comment by endor-force** [comment]
Disabled thermometers in config. 
It seems to create problems for a lot of people. 
Without thermometers the integration works much better overall and I can live without them.
Maybe thermometers setting should be default to false?

**Comment by mgejke** [comment]
Yeah, good idea. Changed it to False as default in hass-sectoralarm.
